// Lists the /stroyka lines that get a recorded voice, for
// scripts/stroyka-voices.py, and writes the clip manifest
// src/lib/stroyka/voiceClips.ts. Run from apps/web:
//   npx tsx scripts/stroyka-voice-lines.ts > /tmp/stroyka-lines.json
// Template lines (opener + remark) are recorded in two parts and played back
// to back, so a few dozen files cover hundreds of combinations.

import { writeFileSync } from 'node:fs';

import { LINES, RADIO_PAIRS } from '../src/lib/stroyka/lines';
import { ALSU_TEMPLATES } from '../src/lib/stroyka/lines/alsu';
import { ILDAR_TEMPLATES } from '../src/lib/stroyka/lines/ildar';
import { MIHALYCH_TEMPLATES } from '../src/lib/stroyka/lines/mihalych';
import { RINAT_TEMPLATES } from '../src/lib/stroyka/lines/rinat';
import { SVETA_TEMPLATES } from '../src/lib/stroyka/lines/sveta';
import { WORKER_TEMPLATES } from '../src/lib/stroyka/lines/worker';
import { RECORDED_SPEAKERS, radioClipKey, voiceKey } from '../src/lib/stroyka/voice';
import { CREW, CREW_VOICE } from '../src/lib/stroyka/crew';
import { INNER_LINES } from '../src/lib/stroyka/lines/inner';

const TEMPLATES = {
  mihalych: MIHALYCH_TEMPLATES,
  rinat: RINAT_TEMPLATES,
  sveta: SVETA_TEMPLATES,
  ildar: ILDAR_TEMPLATES,
  alsu: ALSU_TEMPLATES,
  worker: WORKER_TEMPLATES,
};

// `key` is the file name: the line id plus a fingerprint of its text, so an
// edited line gets a new recording and the old file is removed.
const out: { key: string; speaker: string; text: string }[] = [];
const fileOf = (id: string, text: string) => `${id}-${voiceKey(text)}`;
const keyOf = new Map<string, string>();
const add = (id: string, speaker: string, text: string) => {
  const key = fileOf(id, text);
  keyOf.set(id, key);
  out.push({ key, speaker, text });
};
for (const speaker of RECORDED_SPEAKERS) {
  LINES[speaker]
    .filter((line) => line.id.includes('-h'))
    .forEach((line) => add(line.id, speaker, line.text));
  const t = TEMPLATES[speaker];
  t.openers.forEach((text, o) => add(`${speaker}-o${o}`, speaker, text));
  t.remarks.forEach(([text], r) => add(`${speaker}-r${r}`, speaker, text));
}
RADIO_PAIRS.forEach((pair, n) => {
  for (const side of ['a', 'b'] as const) {
    const speaker = pair[side];
    if (!(RECORDED_SPEAKERS as readonly string[]).includes(speaker)) continue;
    const text = side === 'a' ? pair.aText : pair.bText;
    add(radioClipKey(n, side), speaker, text);
  }
});
// The crew by name, each in their own voice style (crew-<name> in the recorder).
for (const [id, member] of Object.entries(CREW)) {
  member.lines.forEach((text, n) => add(`${CREW_VOICE[id]}-${n}`, CREW_VOICE[id]!, text));
}
// The characters' inner-life lines (lib/stroyka/lines/inner.ts), shown as text
// only (`voiced: false`) until recorded; flip `voiced` once the clips exist.
for (const line of INNER_LINES) {
  if ((RECORDED_SPEAKERS as readonly string[]).includes(line.speaker))
    add(line.id, line.speaker, line.text);
}
// Manifest: spoken text → clips. Hand and radio lines map to one clip; every
// template combination maps to its opener and remark.
const clips: Record<string, string[]> = {};
for (const [id, key] of keyOf) {
  if (/-[or]\d+$/.test(id)) continue;
  clips[key.slice(key.lastIndexOf('-') + 1)] = [key];
}
for (const speaker of RECORDED_SPEAKERS) {
  const t = TEMPLATES[speaker];
  t.openers.forEach((opener, o) =>
    t.remarks.forEach(([remark], r) => {
      clips[voiceKey(opener + remark)] = [
        keyOf.get(`${speaker}-o${o}`)!,
        keyOf.get(`${speaker}-r${r}`)!,
      ];
    }),
  );
}
const body = Object.entries(clips)
  .sort(([a], [b]) => a.localeCompare(b))
  // Prettier's style (single quotes), so the generated file passes format:check.
  .map(([k, v]) => {
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : `'${k}'`;
    return `  ${key}: [${v.map((f) => `'${f}'`).join(', ')}],`;
  })
  .join('\n');
writeFileSync(
  new URL('../src/lib/stroyka/voiceClips.ts', import.meta.url),
  `// Generated by scripts/stroyka-voice-lines.ts — do not edit by hand.\n` +
    `// voiceKey(spoken text) → recorded clips in /audio/stroyka, played in order.\n` +
    `export const VOICE_CLIPS: Record<string, string[]> = {\n${body}\n};\n`,
);
process.stdout.write(JSON.stringify(out, null, 1));
